#!/bin/bash

echo "What is the request number?"

read REQUEST

curl -X GET -k -u jim_wood:d4r12XktoUV2XIrup8BOZvzWMensfWpjIg5RvGJZG "https://api.fyre.ibm.com/rest/v1/?operation=query&request=showrequests&request_id=$REQUEST"
