- hosts: all
  tasks:
  - name: Create a group 'gpfs'
    group:
      name: gpfs

  - name: Create a user 'gpfsadmin' with a home directory
    user:
      name: gpfsadmin
      groups: gpfs
      create_home: yes
      password: $6$vZE.oEh5sZCTpRsJ$mAhlklqa1HdBGEh7McJKf2c4kN0BSzEXPAJrVAXgcIFHtXBueYFsvormBv1J13EXwBwHbT6N4ka2WNe9En5lm/
      # this hashed password is 'passw0rd'
