- hosts: all
#  - name: Stat /etc/issue.net to stop the ssh banner
 #   stat:
  #    path: /etc/issue.net
   # register: issue_exists
  - name: Get stats of a file
    ansible.builtin.stat:
      path: /etc/issue.net
    register: st
    
  - name: rename /etc/issue.net to stop the ssh banner
    command: mv /etc/issue.net /etc/issue.net.bkup
    when: st.stat.exists == True
