- hosts: all
  tasks:
  - name: remove git files from home dir
    file:
      path: /root/labsystems
      state: absent

  - name: Copy git dir to home dir
    synchronize:
      src: /ibm/fs1/git/labsystems
      dest: /root

  - name: Rename /etc/issue.net to stop the ssh banner
    command: mv /etc/issue.net /etc/issue.net.bkup
